name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: generate-snake-game-from-github-contribution-grid
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@v2.2.1
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-snake.svg

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
